<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/session.php';
header('Content-Type: application/json; charset=utf-8');
function cj(array $p,int $s=200):never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function admin_only():void{if(empty($_SESSION['admin_logged_in'])||$_SESSION['admin_logged_in']!==true)cj(['error'=>'Unauthorized'],401);}
function table_ready(PDO $pdo):void{static $r=false;if($r)return;$pdo->exec("CREATE TABLE IF NOT EXISTS organizational_committee(id INT UNSIGNED NOT NULL AUTO_INCREMENT,name_bn VARCHAR(150) NOT NULL DEFAULT '',name_en VARCHAR(150) NOT NULL DEFAULT '',designation_bn VARCHAR(150) NOT NULL DEFAULT '',designation_en VARCHAR(150) NOT NULL DEFAULT '',image_url VARCHAR(500) DEFAULT NULL,status TINYINT(1) NOT NULL DEFAULT 1,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_committee_status_sort(status,sort_order,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$r=true;}
table_ready($pdo);$action=$_GET['action']??'';
if($action==='csrf'){admin_only();cj(['csrf_token'=>Security::generateCSRF()]);}
if($action==='list'){if(!empty($_GET['admin']))admin_only();$where=!empty($_GET['admin'])?'':'WHERE status=1';$s=$pdo->query("SELECT id,name_bn,name_en,designation_bn,designation_en,image_url,status,sort_order FROM organizational_committee {$where} ORDER BY sort_order,id");cj(['committee'=>$s->fetchAll()]);}
if($action==='upload'){admin_only();if(!Security::validateCSRF($_POST['csrf_token']??''))cj(['error'=>'CSRF token mismatch'],419);$f=$_FILES['file']??null;if(!$f||($f['error']??99)!==UPLOAD_ERR_OK)cj(['error'=>'No valid file uploaded'],422);if(($f['size']??0)>5242880)cj(['error'=>'Image must be 5MB or smaller'],422);$mime=function_exists('mime_content_type')?mime_content_type($f['tmp_name']):'';$map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($map[$mime]))cj(['error'=>'Only JPG, PNG and WEBP images are allowed'],422);$dir=__DIR__.'/assets/uploads/committee/';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))cj(['error'=>'Upload directory unavailable'],500);$name=bin2hex(random_bytes(12)).'_'.time().'.'.$map[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.$name))cj(['error'=>'Upload failed'],500);cj(['status'=>'success','url'=>'assets/uploads/committee/'.$name]);}
if($_SERVER['REQUEST_METHOD']!=='POST')cj(['error'=>'Invalid request'],405);admin_only();$in=json_decode(file_get_contents('php://input'),true)?:[];if(!Security::validateCSRF((string)($in['csrf_token']??'')))cj(['error'=>'CSRF token mismatch'],419);
if($action==='save'){$id=(int)($in['id']??0);$v=[trim((string)($in['name_bn']??'')),trim((string)($in['name_en']??'')),trim((string)($in['designation_bn']??'')),trim((string)($in['designation_en']??'')),trim((string)($in['image_url']??'')),!empty($in['status'])?1:0,(int)($in['sort_order']??0)];if($v[0]===''&&$v[1]==='')cj(['error'=>'Member name is required'],422);if($id){$s=$pdo->prepare('UPDATE organizational_committee SET name_bn=?,name_en=?,designation_bn=?,designation_en=?,image_url=?,status=?,sort_order=? WHERE id=?');$s->execute([...$v,$id]);}else{$s=$pdo->prepare('INSERT INTO organizational_committee(name_bn,name_en,designation_bn,designation_en,image_url,status,sort_order) VALUES(?,?,?,?,?,?,?)');$s->execute($v);$id=(int)$pdo->lastInsertId();}cj(['status'=>'success','id'=>$id]);}
if($action==='delete'){$id=(int)($in['id']??0);if($id<=0)cj(['error'=>'Invalid member'],422);$s=$pdo->prepare('SELECT image_url FROM organizational_committee WHERE id=?');$s->execute([$id]);$row=$s->fetch();$pdo->prepare('DELETE FROM organizational_committee WHERE id=?')->execute([$id]);if($row&&!empty($row['image_url'])&&str_starts_with($row['image_url'],'assets/uploads/committee/')){$p=__DIR__.'/'.$row['image_url'];if(is_file($p))@unlink($p);}cj(['status'=>'success']);}
cj(['error'=>'Invalid API action'],404);
